### ISSUE TITLE
iOS 8 orientation issue

### ISSUE THREAD

**Issue by taymer** [gpambrozio/BlockAlertsAnd-ActionSheets#77]
Opening a BlockAlertView and changing device orientation causes a rotation issue: the background and the alertView are no more centered.

**Comment by barrettj** [comment]
Are you using cocoa pods?

**Comment by taymer** [comment]
Yes, but i updated manually.
Il 06/mag/2015 18:42, "Barrett Jacobsen" <notifications@github.com> ha
scritto:

> Are you using cocoa pods?
>
> Sent from my iPhone
>

**Comment by barrettj** [comment]
In your history do you see the following commit: 

1f989833 fix for ios 8 rotation

It should be from 4/17/15

**Comment by taymer** [comment]
Yes on blockbackround.m (if i remember correctly) I wonder you can' t
reproduce the issue.
I've just tested the demo app. Running on iOs 8.3 both on iPhone 6 and ipad
3. Open the alert and rotate the device.

Thanks.
Il 06/mag/2015 19:38, "Barrett Jacobsen" <notifications@github.com> ha
scritto:

> In your history do you see the following commit:
>
> 1f989833 fix for ios 8 rotation
>
> It should be from 4/17/15
>

**Comment by barrettj** [comment]
Interesting.  I definitely see this in the demo project, but not in my actual app that I use the alert in.

**Comment by barrettj** [comment]
Try the commit I just pushed, it disables all custom rotation stuff on iOS 8 which should hopefully fix things.

**Comment by taymer** [comment]
I' ll try tomorrow. I've no mac with me now (it' s evening in Italy ;-] )
Il 06/mag/2015 21:19, "Barrett Jacobsen" <notifications@github.com> ha
scritto:

> Try the commit I just pushed, it disables all custom rotation stuff on iOS
> 8 which should hopefully fix things.
>

**Comment by taymer** [comment]
It's OK.
Thanks a lot.
